package com.examsphere.entity;

public enum AuditAction {
    LOGIN, LOGOUT, REGISTRATION, EMAIL_VERIFIED, PASSWORD_RESET, PASSWORD_CHANGED, PROFILE_UPDATED, EXAM_CREATED, EXAM_UPDATED, EXAM_DELETED, EXAM_PUBLISHED, EXAM_UNPUBLISHED, EXAM_CLOSED, EXAM_STARTED, EXAM_SUBMITTED, INSTRUCTOR_APPROVED, INSTRUCTOR_REJECTED, USER_ACTIVATED, USER_DEACTIVATED
}
